### PR TITLE
feat: support multiple system messages

### PR DESCRIPTION
**Pull request by toxic-johann**
I support multiple system messages in this PR. It will allow users to pass multiple system messages instead of contacting them to string before passing them to the API.

### CODE REVIEW

**Comment by transitive-bullshit** [comment]
Thanks @toxic-johann 🙏 

I think the real fix here is to allow the user to pass a `messages` array to `sendMessage` instead of a static `system` message (or multiple static `system` messages).

Going to close this for now as #416 is imho the correct long-term fix for this

**Comment by toxic-johann** [comment]
OK. I will check if I can help with that PR.

**Comment by transitive-bullshit** [comment]
Thanks @toxic-johann and sorry about that 🙏 

I've been traveling lately and haven't had much time to review PRs, but I'll definitely follow up on this one since it's so important.

**Comment by toxic-johann** [comment]
No worry. Enjoy your vocation.

**Pull request closed without merging**
