### PR TITLE
Add project to project list

### PR DESCRIPTION
**Pull request by Kladdy**

### CODE REVIEW

**Comment by transitive-bullshit** [comment]
Looks cool @Kladdy, but the demo link seems to 404 for me. Is the project ready to be shared more broadly?

**Comment by Kladdy** [comment]
@transitive-bullshit The link to the repo is https://github.com/Kladdy/quizgpt, which should be correct (its a public repo), and the demo link in the README.md links to https://youtu.be/9dmxrIVP4Fs. Do you mean that the YouTube link is not working? I just updated it to https://www.youtube.com/watch?v=9dmxrIVP4Fs (not a shortened link anymore), see if it works now.

**Comment by transitive-bullshit** [comment]
@Kladdy I'm talking about https://quizgpt.vercel.app which is the main link at the top of the repo (not in the readme, but in github's metadata)

**Comment by Kladdy** [comment]
@transitive-bullshit Ah, sorry, I see! That was a mistake, it can only be run locally right now actually. I removed the Vercel link.

**Comment by transitive-bullshit** [comment]
No worries && thanks 😊

**Comment by Kladdy** [comment]
Thanks for making such an awesome client! 🥳

**Pull request merged**
