### PR TITLE
Proxy auth

### PR DESCRIPTION
**Pull request by timmsGithub**
This adds the possibility to use a proxy in the format user:pass@ip:port

### CODE REVIEW

**Comment by transitive-bullshit** [comment]
This looks great @timmsGithub 🙏

I will take a closer look at it tomorrow. Just making sure, this shouldn't change anything for people who currently are using the proxy support without auth, right?

**Comment by timmsGithub** [comment]
I think it should work but feel free to test it before you merge it :)

**Review by transitive-bullshit — APPROVED** [review]

**Comment by transitive-bullshit** [comment]
Thanks @timmsGithub 🙏

**Comment by transitive-bullshit** [comment]
https://github.com/transitive-bullshit/chatgpt-api/releases/tag/v3.3.2

**Pull request merged**
