### PR TITLE
Node JS lib to get chat gpt auth token to use with ChatGPTUnofficialProxyAPI

### PR DESCRIPTION
**Pull request by AllanOricil**
this lib does the same thing as the python implementation

### CODE REVIEW

**Comment by AllanOricil** [comment]
@transitive-bullshit if you and @acheong08 don't like the idea of this node package I can just delete it... I created for my own usage anyways.

**Comment by acheong08** [comment]
The reason I rewrote the package in pure requests was so people could port it over to other languages. Good work

**Comment by AllanOricil** [comment]
> The reason I rewrote the package in pure requests was so people could port it over to other languages. Good work

@acheong08  you are the one who did the amazing work.
One question, do you know how to actually refresh tokens? I tried reusing the same session but it is always returning the same token instead of recreating a new one. Do u know if there is a route to invalidate a given token?

**Comment by acheong08** [comment]
https://github.com/acheong08/OpenAIAuth/blob/3b80200d4399d975c7651211b799a408f0aee579/src/OpenAIAuth.py#L306-L325

**Comment by acheong08** [comment]
https://explorer.api.openai.com/api/auth/session

**Comment by AllanOricil** [comment]
So the only way to get a new token is by getting a new session token?

**Comment by acheong08** [comment]
You can get it with email/password if you log in again

**Comment by acheong08** [comment]
but yes, `__Secure-next-auth.session-token` is required for accessToken

**Comment by transitive-bullshit** [comment]
Thanks @AllanOricil 🙏 

Just getting around to this now :)

**Pull request merged**
