### PR TITLE
Fix prompt length calculation

### PR DESCRIPTION
**Pull request by alxmiron**
Current `_buildMessages()` calculates tokens in prompt in a wrong way - there's a small difference with a usage amount that comes from ChatGPT (in non-stream mode).
I fix it, picking the logic from [here](https://learn.microsoft.com/en-us/azure/cognitive-services/openai/how-to/chatgpt?pivots=programming-language-chat-completions#managing-conversations)
Now our estimated `numTokens` should be equal to `message.detail.usage.prompt_tokens`

### CODE REVIEW

**Comment by zhujunsan** [comment]
Better to check the model and then calc. gpt3.5 and 4 seems calc differently.

**Comment by zhujunsan** [comment]
I also make the change in #546, but your code looks better 😀

**Comment by zhujunsan** [comment]
after test, at least in gpt-3.5, tokens_per_message is 5. I think it's one missing `\n` that's not calculated

**Review by hexiaokang — APPROVED** [review]

**Comment by zhujunsan** [comment]
Is there anyone to merge or review this pr?

**Comment by transitive-bullshit** [comment]
This project is undergoing a major revamp; closing out old PRs as part of the prep process.

Sorry I never got around to reviewing this PR. The `chatgpt` package is pretty outdated at this point. I recommend that you use the [openai](https://github.com/openai/openai-node) package or the [openai-fetch](https://github.com/dexaai/openai-fetch) package.

**Pull request closed without merging**
