### PR TITLE
feat: support open ai message array

### PR DESCRIPTION
**Pull request by toxic-johann**
Modify the `sendMessage` to allow open ai message array

### CODE REVIEW

**Comment by chipcop106** [comment]
Please, we need this feature

**Comment by nightwalker89** [comment]
Which case need message array?

**Comment by toxic-johann** [comment]
> Which case need message array?
 Such as multiple system message https://github.com/transitive-bullshit/chatgpt-api/pull/551

**Comment by gtn1024** [comment]
Need this feature. Is it possible to be merged to mainline? @transitive-bullshit

**Comment by liuzhenyulive** [comment]
I also need this feature for a translation application and I am looking forward to its implementation.

**Comment by liuzhenyulive** [comment]
Hi guys, has any responded to this yet?

**Comment by transitive-bullshit** [comment]
This project is undergoing a major revamp; closing out old PRs as part of the prep process. Sorry!

This was a good change and much-needed, but the `chatgpt` package is pretty outdated at this point. I recommend that you use the [openai](https://github.com/openai/openai-node) package or the [openai-fetch](https://github.com/dexaai/openai-fetch) package.

**Pull request closed without merging**
