### PR TITLE
Conversation support

### PR DESCRIPTION
**Pull request by simon300000**
Was able to make Conversation work with some trial and error.

Added a new class called `Conversation` and changed some opts of `sendMessage`, maybe not the best design so please give suggestions

Result:
image

(see src/demo-conversation.ts)

Before:
<details>
image

  ```ts
import dotenv from 'dotenv-safe'
import { oraPromise } from 'ora'

import { ChatGPTAPI } from '.'

dotenv.config()

/**
 * Example CLI for testing functionality.
 *
 * ```
 * npx tsx src/demo.ts
 * ```
 */
async function main() {
  const api = new ChatGPTAPI({ sessionToken: process.env.SESSION_TOKEN })
  await api.ensureAuth()

  const prompt = 'What is OpenAI?'

  const response = await oraPromise(api.sendMessage(prompt, { conversationId: '0c382256-d267-4dd4-90e3-a01dd22c20a1' }), {
    text: prompt
  })

  console.log(response)

  const prompt2 = 'Continue'

  console.log(
    await oraPromise(api.sendMessage(prompt2, { conversationId: '0c382256-d267-4dd4-90e3-a01dd22c20a1' }), {
      text: prompt2
    })
  )

  console.log(
    await oraPromise(api.sendMessage(prompt2, { conversationId: '0c382256-d267-4dd4-90e3-a01dd22c20a1' }), {
      text: prompt2
    })
  )
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
  ```
</details>

### CODE REVIEW

**Comment by transitive-bullshit** [comment]
This would fix #29 

@simon300000 Thanks so much for the PR! 🙏 

Give me a bit of time to review and consider different possible APIs.

**Review by transitive-bullshit — APPROVED** [review]
Thank you so much @simon300000.

I spent awhile playing with your PR locally just now. I really like the API 💯 

There are a few small tweaks I'll be making w.r.t. comments and exports, but overall this is an amazing improvement. Will merge & then hope to get a new version released in the next few hours.

Thanks again! 🙏

**Comment by deanylev** [comment]
I consistently (as in, every single time) get 503s and 429s when passing a conversation and parent message ID. Quite strange.

**Comment by deanylev** [comment]
I'm also using `onConversationResponse`. I have not had a problem when rapid firing requests without these parameters, but I will give your suggestion a shot.

**Pull request merged**
