### PR TITLE
Added timeouts for onProgess

### PR DESCRIPTION
**Pull request by Vadko**
resolves https://github.com/transitive-bullshit/chatgpt-api/issues/410

tested both official&unofficial api

### CODE REVIEW

**Comment by Vadko** [comment]
@transitive-bullshit 🙏

**Comment by RainEggplant** [comment]
Yes, I think this feature would be helpful when the response text is long so that it doesn't get aborted during streaming. @transitive-bullshit

**Comment by transitive-bullshit** [comment]
hey sorry @Vadko, this PR is more complicated and I think it could have some unintended consequences so I've been putting off reviewing it.

**Comment by Vadko** [comment]
@transitive-bullshit I've updated branch, it is ready to review

**Comment by Vadko** [comment]
@transitive-bullshit any chance you can look into it?🙏

**Comment by transitive-bullshit** [comment]
This project is undergoing a major revamp; closing out old PRs as part of the prep process.

This was a good change, but the `chatgpt` package is pretty outdated at this point. I recommend that you use the [openai](https://github.com/openai/openai-node) package or the [openai-fetch](https://github.com/dexaai/openai-fetch) package.

**Pull request closed without merging**
