### PR TITLE
Add conversation history support

### PR DESCRIPTION
**Pull request by f1nniboy**
This PR adds support for fetching conversation history, deleting conversations and generating summary titles using OpenAI's API. I also added a generic `fetch()` function, for future support of the `/moderation` endpoint.

What I have also noticed, is that the NopeCHA code *sometimes* enters the API key twice, resulting in it being invalid. This should also fix that, but you might need to do some more testing.

### CODE REVIEW

**Comment by transitive-bullshit** [comment]
This looks awesome @f1nniboy 🙏

I will hopefully be able to review this in-depth tomorrow.

**Comment by transitive-bullshit** [comment]
Wanted to say again sorry @f1nniboy for not reviewing yet. PRs with multiple changes are always harder to review.

Also, just spending time with family for Christmas at the moment. 🎄 💕 But I promise to get to get to it soon.

**Comment by transitive-bullshit** [comment]
Sorry @f1nniboy; I'm going to have to close this. Your PR was excellent; I just don't have the bandwidth to support additional APIs beyond the core `sendMessage`. Sorry again && thanks for taking the time to contribute.

**Comment by ciekawy** [comment]
I would love to see this merged! This is an important thing I am missing in one derivate project

**Pull request closed without merging**
