### PR TITLE
feat: support ChatGPTAPIBrowser use cutom model like gpt-4

### PR DESCRIPTION
**Pull request by SmileSmith**

### CODE REVIEW

**Comment by SmileSmith** [comment]
The reason I continue to use v3 is: My service is for internal use by employees within a Chinese company(Proxy methods are prone to being blocked.), and I'm concerned that using the v5 ChatGPTUnofficialProxyAPI may pose a risk of privacy leaks.

**Comment by UNIDY2002** [comment]
Is there a plan for this feature to be released? I could patch it by myself, but it would be more convenient if there is a new release. Thank you!

**Comment by SmileSmith** [comment]
@transitive-bullshit Can help publish it to v3? please

**Comment by transitive-bullshit** [comment]
@SmileSmith I'm no longer maintaining v3. The code is publicly available, but I strongly recommend using the official API going forwards. I have it on good authority that anyone using unofficial methods like v3 will receive bans from OpenAI.

**Comment by SmileSmith** [comment]
> @SmileSmith I'm no longer maintaining v3. The code is publicly available, but I strongly recommend using the official API going forwards. I have it on good authority that anyone using unofficial methods like v3 will receive bans from OpenAI.

got it，thanks~ :smile:

**Pull request merged**
