### PR TITLE
docs: add option for how to automatically refresh session token to readme

### PR DESCRIPTION
**Pull request by Mereithhh**
Add a choice to automatically get session toekn :)

### CODE REVIEW

**Comment by transitive-bullshit** [comment]
Hey @Mereithhh, thanks for the PR 🙏 

Before merging this, a few questions:

1. What's the thought process behind exposing this functionality only as an HTTP API? Why not as a node.js package so it's easier to call?

2. Have you run into any captchas?

The [solution](https://github.com/transitive-bullshit/chatgpt-twitter-bot/blob/main/src/openai-auth.ts) I'm using at the moment for my Twitter bot uses the [python revChatGPT module](https://github.com/acheong08/ChatGPT).

I'd love to point people to a non-python solution, but I'd like to offer something easier to integrate with than a local HTTP server.

Thoughts?

**Comment by Mereithhh** [comment]
## Why HTTP API

1. This is more versatile, regardless of the programming language used. It can be invoked by any language.
2. Inside my solution, I use playwright to simulate login behavior , but installing playwright and headless browser dependencies is cumbersome. and installing these will make the environment in which the script runs dirtier.
3. So I made docker images, easy to deploy , easy to clean, easy to call.
4. In my country, I can't login openai directly. So I need to have the certification service on another VPS.
5. And more, if the IP is blocked, I can quickly deploy the service on another VPS.

## Captchas
I haven't come across this.
## About this PR
I just want to give everyone another option, especially people who are in a similar situation to me.

What you said also makes sense, I will make a separate package for the part of obtaining the session token later.

**Comment by Mereithhh** [comment]
I appended the commit and now it's a separate package. 😁

**Comment by transitive-bullshit** [comment]
Aye; I was planning on merging this @Mereithhh , but I woke up today to find that #96 has completely changed the requirements for automating login. I've tried playwright, puppeteer, and puppeteer-extra + puppeteer-extra-plugin-stealth and haven't had any luck so far.

Going to close this for now as outdated since the current automated browser solutions won't work w/ Cloudflare protections in place. Feel free to create a new PR and update #96 if you figure out a workaround.

Thanks!

**Pull request closed without merging**
