### PR TITLE
Introduce an impelement of onProgress in browserAPI.

### PR DESCRIPTION
**Pull request by bhhbazinga**
Use websocket to implement the onProgress method in the browser API environment, and introduce a new ProgressResponse type which contain new data fragments received each time.

### CODE REVIEW

**Comment by transitive-bullshit** [comment]
Interesting approach @bhhbazinga 🔥 

I was considering using https://pptr.dev/api/puppeteer.page.exposefunction to allow the injected script to call a function in node.js for progress. It would remove the need for all the websocket stuff.

Thoughts on the two approaches?

**Comment by transitive-bullshit** [comment]
btw, it looks like CI is failing because the `ws` package is missing.

**Comment by bhhbazinga** [comment]
> Interesting approach @bhhbazinga 🔥
> 
> I was considering using https://pptr.dev/api/puppeteer.page.exposefunction to allow the injected script to call a function in node.js for progress. It would remove the need for all the websocket stuff.
> 
> Thoughts on the two approaches?



> Interesting approach @bhhbazinga 🔥
> 
> I was considering using https://pptr.dev/api/puppeteer.page.exposefunction to allow the injected script to call a function in node.js for progress. It would remove the need for all the websocket stuff.
> 
> Thoughts on the two approaches?



> Interesting approach @bhhbazinga 🔥
> 
> I was considering using https://pptr.dev/api/puppeteer.page.exposefunction to allow the injected script to call a function in node.js for progress. It would remove the need for all the websocket stuff.
> 
> Thoughts on the two approaches?

puppeteer.page.exposefunction seems like a more lightweight approach, have you tried it?

**Comment by bhhbazinga** [comment]
> Interesting approach @bhhbazinga 🔥
> 
> I was considering using https://pptr.dev/api/puppeteer.page.exposefunction to allow the injected script to call a function in node.js for progress. It would remove the need for all the websocket stuff.
> 
> Thoughts on the two approaches?

puppeteer.page.exposefunction seems like a more lightweight way, have you tried it?

**Comment by bhhbazinga** [comment]
> btw, it looks like CI is failing because the `ws` package is missing.

I'm not familiar with node.js, but it runs fine in my environment, maybe because I didn't add dependencies in package.json?

**Comment by transitive-bullshit** [comment]
> > btw, it looks like CI is failing because the `ws` package is missing.
> 
> I'm not familiar with node.js, but it runs fine in my environment, maybe because I didn't add dependencies in package.json?

If you have `ws` installed globally, then it would work for you locally, but it won't be available to other people unless it's installed into your package dependencies. Since this project is using `pnpm` to manage dependencies (instead of the default `npm` package manager), you'd have to install `pnpm` and then run `pnpm add ws`.

With that being said, I do think we'll want to go with the `exposeFunction` method. It's a lot simpler.

**Comment by bincooo** [comment]
I did, based on page.exposefunction to make the asynchronous result of the stream response to ChatGPTAPIBrowser。
But maybe it's not so good。
Examples are at demos/demo-conversation-browser.ts :
https://github.com/bincooo/cdn/raw/main/cgpt.zip

**Pull request closed without merging**
