### PR TITLE
add cjs export

### PR DESCRIPTION
**Pull request by oceanlvr**

### CODE REVIEW

**Comment by transitive-bullshit** [comment]
@oceanlvr I appreciate the PR 🙏 

However, I generally don't like publishing packages with CJS exports unless there is a good reason for it. Trying to follow the spirit of Sindre Sorhus' [approach](https://github.com/sindresorhus/meta/discussions/15).

Is there a reason why ESM isn't working for you, or do you just see it as a best practice to publish both formats?

**Comment by oceanlvr** [comment]
Yes, I also like Prue ESM export. But when I develop the probot APP. pure `ESM` not working. https://github.com/probot/probot/issues/1684

So Maybe we could export both `esm` and `cjs` like this https://antfu.me/posts/publish-esm-and-cjs

**Comment by transitive-bullshit** [comment]
Sounds good. In the past, I've just run into so many issues by not being able to rely on ESM-only libs in dual cjs+ESM packages. It may work at build time and publishing to NPM, but it's a PITA to deal with long-term as a maintainer.

I merged for now and it'll be dual cjs+esm for the next major release with #9, but if it becomes a burden, I will have to revert.

**Comment by transitive-bullshit** [comment]
Thanks!

**Pull request merged**
