### PR TITLE
Re-add cjs support, fixed "Error [ERR_REQUIRE_ESM]: require() of ES Module not supported."

### PR DESCRIPTION
**Pull request by GoneTone**
Merge and re-open a pull request

- `node-fetch` downgraded to v2.6.7
- `remark` downgraded to v13.0.0
- `strip-markdown` downgraded to v4.2.0

### CODE REVIEW

**Comment by transitive-bullshit** [comment]
@FarazPatankar @GoneTone I'm not sure I want to commit to supporting commonjs.

It's mostly deprecated at this point, and it would place an extra burden on the maintenance of this package in the long-term.

Maybe as a compromise, I could merge, publish a version that uses commonjs, and then remove support after that?

**Comment by FarazPatankar** [comment]
Yeah, that's understandable. It'd be great if you could publish the one-off version though!

**Comment by transitive-bullshit** [comment]
Thanks so much @GoneTone 🙏 

I'll be publishing a new version now and then sticking with ESM-only on the main branch from then on unless I get a lot of flack.

**Comment by transitive-bullshit** [comment]
CommonJS support via this PR: https://github.com/transitive-bullshit/chatgpt-api/releases/tag/v1.3.0

**Pull request merged**
